name: Build

on:
    push:
        tags-ignore:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18

            - name: Build
              run: |
                  CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-w -s" -o MCSM-Bot_windows_amd64.exe
                  CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -ldflags="-w -s" -o MCSM-Bot_windows_arm64.exe
                  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o MCSM-Bot_linux_amd64
                  CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-w -s" -o MCSM-Bot_linux_arm64
                  CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-w -s" -o MCSM-Bot_darwin_amd64
                  CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="-w -s" -o MCSM-Bot_darwin_arm64

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3.1.0
              with:
                  name: MCSM-Bot
                  path: |
                      MCSM-Bot_windows_amd64.exe
                      MCSM-Bot_windows_arm64.exe
                      MCSM-Bot_linux_amd64
                      MCSM-Bot_linux_arm64
                      MCSM-Bot_darwin_amd64
                      MCSM-Bot_darwin_arm64

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  title: Development Build
                  prerelease: true
                  files: |
                      MCSM-Bot_windows_amd64.exe
                      MCSM-Bot_windows_arm64.exe
                      MCSM-Bot_linux_amd64
                      MCSM-Bot_linux_arm64
                      MCSM-Bot_darwin_amd64
                      MCSM-Bot_darwin_arm64
