name: Go

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18

            - name: Build
              run: |
                  CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o MCSM-Bot_windows_amd64.exe
                  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o MCSM-Bot_linux_amd64
                  CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o nMCSM-Bot_darwin_amd64

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3.1.0
              with:
                  name: MCSM-Bot
                  path: ./
