name: Releases

on:
    push:
        tags:
            - v*

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18

            - name: Build
              run: |
                  CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o MCSM-Bot_windows_amd64.exe
                  CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -o MCSM-Bot_windows_arm64.exe
                  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o MCSM-Bot_linux_amd64
                  CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o MCSM-Bot_linux_arm64
                  CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o MCSM-Bot_darwin_amd64
                  CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o MCSM-Bot_darwin_arm64

            - name: Get tag
              id: tag
              uses: dawidd6/action-get-tag@v1
              with:
                  strip_v: true

            - name: Use tag
              run: echo ${{steps.tag.outputs.tag}}

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: ${{ steps.get_version.outputs.VERSION }}
                  title: ${{ steps.get_version.outputs.VERSION }}
                  prerelease: false
                  files: |
                      MCSM-Bot_windows_amd64.exe
                      MCSM-Bot_windows_arm64.exe
                      MCSM-Bot_linux_amd64
                      MCSM-Bot_linux_arm64
                      MCSM-Bot_darwin_amd64
                      MCSM-Bot_darwin_arm64
