name: Go

on:
    push:
        branches: ["main"]
        tags:
            - "v*"
    pull_request:
        branches: ["main"]

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18

            - name: Build
              run: |
                  CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o MCSM-Bot_windows_amd64.exe
                  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o MCSM-Bot_linux_amd64
                  CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o MCSM-Bot_darwin_amd64

            - name: Get Version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: ${{ steps.get_version.outputs.VERSION }}
                  title: ${{ steps.get_version.outputs.VERSION }}
                  files: |
                      MCSM-Bot_windows_amd64.exe
                      MCSM-Bot_linux_amd64
                      MCSM-Bot_darwin_amd64
